AdventureWorksWebAPI/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AdventureWorksWebAPI.Controllers
{
    public class ImagesController : Controller
    {
        private AdventureWorks2012Entities db = new AdventureWorks2012Entities();

        // GET: Images/Thumbnail/5
        public ActionResult Thumbnail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductPhoto productPhoto = db.ProductPhotoes.Find(id);
            if (productPhoto == null)
            {
                return HttpNotFound();
            }

            return File(productPhoto.ThumbNailPhoto, "image/jpg");
        }

        // GET: Images/Photo/5
        public ActionResult Photo(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductPhoto productPhoto = db.ProductPhotoes.Find(id);
            if (productPhoto == null)
            {
                return HttpNotFound();
            }

            return File(productPhoto.LargePhoto, "image/jpg");
        }
    
    }
}

AdventureWorksWebAPI/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdventureWorksWebAPI;
using AdventureWorksWebAPI.Models;

namespace AdventureWorksWebAPI.Controllers
{
    public class ProductsController : Controller
    {
        private AdventureWorks2012Entities db = new AdventureWorks2012Entities();


        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.ProductModel).Include(p => p.ProductProductPhotoes)
                                      //.Where(p => (p.ProductProductPhotoes.FirstOrDefault().ProductPhotoID > 1))
                                      .OrderBy(p => p.Name);
            return View(products.ToList());
        }


        // GET: Products/Category/T
        public ActionResult Category(string category)
        {
            var result = "Products";
            var products = db.Products.Include(p => p.ProductSubcategory).Include(p => p.ProductProductPhotoes)
                                      .OrderBy(p => p.Name);

            if (category == "M" || category == "R" || category == "T")
            {
                result = (category == "M") ? "Mountain Bikes" : (category == "R") ? "Road Bikes" : "Tour Bikes";
                products = db.Products.Include(p => p.ProductSubcategory).Include(p => p.ProductProductPhotoes)
                                      .Where(p => (p.ProductLine.Equals(category) && p.ProductSubcategory.ProductCategory.Name == "Bikes"))
                                      .OrderBy(p => p.Name);
            }
            else if (category == "A")
            {
                result = "Accessories";
                products = db.Products.Include(p => p.ProductSubcategory).Include(p => p.ProductProductPhotoes)
                                      .Where(p => (p.ProductSubcategory.ProductCategory.Name == "Accessories"))
                                      .OrderBy(p => p.Name);
            }
            else if (category == "C")
            {
                result = "Clothing";
                products = db.Products.Include(p => p.ProductSubcategory).Include(p => p.ProductProductPhotoes)
                                      .Where(p => (p.ProductSubcategory.ProductCategory.Name == "Clothing"))
                                      .OrderBy(p => p.Name);
            }
            else if (category == "P")
            {
                result = "Parts";
                products = db.Products.Include(p => p.ProductSubcategory).Include(p => p.ProductProductPhotoes)
                                      .Where(p => (p.ProductSubcategory.ProductCategory.Name == "Components"))
                                      .OrderBy(p => p.Name);
            }

            return View(new ProductsVM { Category = result, Products = products.ToList() });
        }


        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.ProductModelID = new SelectList(db.ProductModels, "ProductModelID", "Name");
            ViewBag.ProductSubcategoryID = new SelectList(db.ProductSubcategories, "ProductSubcategoryID", "Name");
            ViewBag.SizeUnitMeasureCode = new SelectList(db.UnitMeasures, "UnitMeasureCode", "Name");
            ViewBag.WeightUnitMeasureCode = new SelectList(db.UnitMeasures, "UnitMeasureCode", "Name");
            ViewBag.ProductID = new SelectList(db.ProductDocuments, "ProductID", "ProductID");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,Size,SizeUnitMeasureCode,WeightUnitMeasureCode,Weight,DaysToManufacture,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductModelID = new SelectList(db.ProductModels, "ProductModelID", "Name", product.ProductModelID);
            ViewBag.ProductSubcategoryID = new SelectList(db.ProductSubcategories, "ProductSubcategoryID", "Name", product.ProductSubcategoryID);
            ViewBag.SizeUnitMeasureCode = new SelectList(db.UnitMeasures, "UnitMeasureCode", "Name", product.SizeUnitMeasureCode);
            ViewBag.WeightUnitMeasureCode = new SelectList(db.UnitMeasures, "UnitMeasureCode", "Name", product.WeightUnitMeasureCode);
            ViewBag.ProductID = new SelectList(db.ProductDocuments, "ProductID", "ProductID", product.ProductID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductModelID = new SelectList(db.ProductModels, "ProductModelID", "Name", product.ProductModelID);
            ViewBag.ProductSubcategoryID = new SelectList(db.ProductSubcategories, "ProductSubcategoryID", "Name", product.ProductSubcategoryID);
            ViewBag.SizeUnitMeasureCode = new SelectList(db.UnitMeasures, "UnitMeasureCode", "Name", product.SizeUnitMeasureCode);
            ViewBag.WeightUnitMeasureCode = new SelectList(db.UnitMeasures, "UnitMeasureCode", "Name", product.WeightUnitMeasureCode);
            ViewBag.ProductID = new SelectList(db.ProductDocuments, "ProductID", "ProductID", product.ProductID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,Size,SizeUnitMeasureCode,WeightUnitMeasureCode,Weight,DaysToManufacture,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductModelID = new SelectList(db.ProductModels, "ProductModelID", "Name", product.ProductModelID);
            ViewBag.ProductSubcategoryID = new SelectList(db.ProductSubcategories, "ProductSubcategoryID", "Name", product.ProductSubcategoryID);
            ViewBag.SizeUnitMeasureCode = new SelectList(db.UnitMeasures, "UnitMeasureCode", "Name", product.SizeUnitMeasureCode);
            ViewBag.WeightUnitMeasureCode = new SelectList(db.UnitMeasures, "UnitMeasureCode", "Name", product.WeightUnitMeasureCode);
            ViewBag.ProductID = new SelectList(db.ProductDocuments, "ProductID", "ProductID", product.ProductID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdventureWorksWebAPI/Views/Products/Category.cshtml
@model AdventureWorksWebAPI.Models.ProductsVM

@{
    ViewBag.Title = @Model.Category;
}

<h2>@Model.Category</h2>

<table class="table">
    <tr>
        <th>
            &nbsp;
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().ProductNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().ListPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().Size)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().ProductLine)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().Class)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.Products.FirstOrDefault().Style)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Products) {
    <tr>
        <td>
            <a href="@Url.Action("Details", new { id = item.ProductID })"><img src='@Url.Action( "Thumbnail", "Images", new { id = item.ProductProductPhotoes.First().ProductPhotoID } )' />
</a></td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ListPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductLine)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Class)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Style)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductID })
        </td>
    </tr>
}

</table>

AdventureWorksWebAPI/Views/Products/Delete.cshtml
@model AdventureWorksWebAPI.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MakeFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MakeFlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishedGoodsFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishedGoodsFlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SafetyStockLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SafetyStockLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReorderPoint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReorderPoint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StandardCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StandardCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ListPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaysToManufacture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaysToManufacture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductLine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductLine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Style)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiscontinuedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiscontinuedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rowguid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rowguid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductModel.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductModel.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductSubcategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductSubcategory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitMeasure.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitMeasure.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitMeasure1.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitMeasure1.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDocument.ProductID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDocument.ProductID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdventureWorksWebAPI/Views/Products/Details.cshtml
@model AdventureWorksWebAPI.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />

    <div class="dl-horizontal">
        <img src='@Url.Action( "Photo", "Images", new { id = Model.ProductProductPhotoes.First().ProductPhotoID } )' />
    </div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MakeFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MakeFlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishedGoodsFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishedGoodsFlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SafetyStockLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SafetyStockLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReorderPoint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReorderPoint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StandardCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StandardCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ListPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaysToManufacture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaysToManufacture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductLine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductLine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Style)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiscontinuedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiscontinuedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rowguid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rowguid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductModel.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductModel.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductSubcategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductSubcategory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitMeasure.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitMeasure.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitMeasure1.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitMeasure1.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDocument.ProductID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDocument.ProductID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AdventureWorksWebAPI/Views/Products/Index.cshtml
@model IEnumerable<AdventureWorksWebAPI.Product>

@{
    ViewBag.Title = "Products";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            &nbsp;
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ListPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductLine)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Style)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <a href="@Url.Action("Details", new { id = item.ProductID })"><img src='@Url.Action( "Thumbnail", "Images", new { id = item.ProductProductPhotoes.First().ProductPhotoID } )' />
</a></td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ListPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductLine)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Class)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Style)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductID })
        </td>
    </tr>
}

</table>